apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-actions
  annotations:
    github.com/project-slug: submittable/github-actions
  tags:
    - github
spec:
  type: other
  lifecycle: development
  owner: infrastructure
