name: Reusable Workflow 3.0

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # Run Tests, SonarQube Scans, Build and Publish Docker Image
  ci:
      uses: submittable/github-actions/.github/workflows/ci.yml@main
      
      # NOTE: you do not have to fill out the values below.
      # The values below are defaults and some such as repo_name
      # have functions to detect the repo name. So, if you'd like
      # to override the defaults then uncomment 'with' and the fields below
      # and update them.
      
      # with:
        # ---------------------------------------------------------
        # General project properties
        # ---------------------------------------------------------
        # repo_name: 'your-repo'                # Name of the repository
        # image_name: 'submittable/your-repo'   # Name of the owner and repository
        # sem-release: true                     # Enable or disable a semantic release
        # file: 'Dockerfile'                    # Dockerfile name
        # context: .                            # Directory of the Dockerfile

        # ---------------------------------------------------------
        # Set build type for Nodejs, Python, or .NET
        # ---------------------------------------------------------
        # file_check_path_python: "requirements.txt"
        # file_check_path_nodejs: "package.json"
        # file_check_path_dotnet: "*.sln"

        # ---------------------------------------------------------
        # Set builder version
        # ---------------------------------------------------------
        # nodejs_version: '15.x'
        # dotnet_version: '5.0.x'
        # python_version: '3.6'

        # ---------------------------------------------------------
        # Unit tests folder location
        # ---------------------------------------------------------
        # file_check_path_nodejs_test: "src/__tests__/*"
        # file_check_path_python_test: "tests/*"
        # file_check_path_dotnet_test: "*.Test/*.Test.csproj"
        
        # ---------------------------------------------------------
        # Enable or disable SonarQube scan
        # ---------------------------------------------------------
        # DEPRECATED: run SonarQube scan when unit tests are identified
        # sonar-python: true
        # sonar-dotnet: false
        # sonar-nodejs: false
        
        # ---------------------------------------------------------
        # For .NET SonarQube scan only
        # ---------------------------------------------------------
        # dotnetbuildarguments: 'src/Submittable.Api' # Set the path to dotnet build for SonarQube
      secrets:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
