name: Reusable Workflow 2.0
#This reusable workflows tests and scans the code for any vulnerabilities. Currently working on Python and Nodejs projects.

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  #Run tests & Sonar Scan
  test:
      uses: submittable/github-actions/.github/workflows/test-ci.yml@main
      with:
        repo_name: submittable-test-python-repo #CHANGE this to the name of the project
      secrets:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  #Dockerize app      
  docker:
      needs: test
      uses: submittable/github-actions/.github/workflows/reusable-docker.yml@main
      with:
      #this is a variable configured within the called workflow. in this case the image_name will be the repo name
        image_name: ${{ github.repository }}
        context: .
      secrets:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}