name: Reusable Workflow 2.0
#This reusable workflows tests and scans the code for any vulnerabilities. Currently working on Python and Nodejs projects.

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  #Run tests & Sonar Scan
  test:
      uses: submittable/github-actions/.github/workflows/test.yml@main
      secrets:
#         GITHUB_TOKEN: ${{ secrets.token }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  
  #Dockerize app      
  docker-frontend:
      needs: test
      uses: submittable/github-actions/.github/workflows/reusable-docker.yml@main
      with:
      #this is a variable configured within the called workflow. in this case the image_name will be the repo name
        image_name: ${{ github.repository }}
        #context: CHANGEME
      secrets:
#         GITHUB_TOKEN: ${{ secrets.token }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #docker-backend:
      #uses: submittable/github-actions/.github/workflows/reusable-docker.yml@main
      #with:
      ##this is a variable configured within the called workflow. in this case the image_name will be the repo name
        #image_name: ${{ github.repository }}
        #context: CHANGEME
      #secrets:
        #GITHUB_TOKEN: ${{ secrets.token }}
        #SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}