name: Reusable Workflow 2.0
#This reusable workflows tests and scans the code for any vulnerabilities. Currently working on Python and Nodejs projects.

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  #Run Tests, Sonar Scans, Build and Publish Docker Image
  test:
      uses: submittable/github-actions/.github/workflows/ci.yml@main
      with:
        repo_name: submittable-test-python-repo #CHANGE this to the name of the project
      secrets:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}