name: Image Build and Publish

on:
  push:
    branches: 
      - main
    paths:
      - 'self-hosted-runners/Dockerfile'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      # Reads the latest tag on the repo and increments its minor verions
      # Increment style can be changed by including a #major, #minor, or #patch in a commit message
      - name: Bump version and push tag
        id: tag_version
        uses: submittable/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          VERBOSE: true
          WITH_V: false

      # Attempt to make the REF string valid docker tag syntax
      - name: Extract source branch/pr name
        shell: bash
        run: |
          TEMP=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "##[set-output name=branch;]$(echo ${TEMP///-})"
        id: extract_ref_tag

      # Collate the image name, tags, and labels for push command
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=raw,value=${{ steps.tag_version.outputs.new_tag }}
            type=raw,value=${{ steps.extract_ref_tag.outputs.branch }}
            type=raw,value=${{ GitHub.sha }}

      # Build, Tag and Push the docker image to Github Container Registry
      - name: Build, Tag and Push Docker Image
        uses: docker/build-push-action@v2.7.0
        id: image_build
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          context: self-hosted-runners
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Creates a Github release with the new semantic version, if main or PR to main
      - name: Create a GitHub Semantic release
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      # TODO Deployment step here looks like updating ArgoCD Application and Self Hosted Runner manifests to use this new image

      # Sends a slack notification to slack build channel on failure
      - name: Report Failure to Slack
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: submittable/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BUILDS_SLACK_WEBHOOK }}

      # Sends a slack notification to slack build channel
      - name: Report Success to Slack
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: submittable/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILDS_SLACK_WEBHOOK }}
          SLACK_MESSAGE: Job for Release ${{ steps.tag_version.outputs.new_tag }} completed successfully.