name: Resuable Docker Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      context:
        description: 'adds the context path to the dockerfile'
        default: '.'
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile"
      
      - name: Set up QEMU
        if: steps.check_files.outputs.files_exists == 'true'
        uses: docker/setup-qemu-action@v1
        
      #This action will set up and boot a builder that can be used in the workflow.
      - name: Set up Docker Buildx
        if: steps.check_files.outputs.files_exists == 'true'
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to GitHub Container Registry
        if: steps.check_files.outputs.files_exists == 'true'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Reads the latest tag on the repo and increments its minor verions
      # Increment style can be changed by including a #major, #minor, or #patch in a commit message
      - name: Bump version and push tag
        if: steps.check_files.outputs.files_exists == 'true'
        id: tag_version
        uses: submittable/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: false
          #INITIAL_VERSION: #Set initial version before bump. Default 0.0.0

      # Attempt to make the REF string valid docker tag syntax
      - name: Extract source branch/pr name
        if: steps.check_files.outputs.files_exists == 'true'
        shell: bash
        run: |
          TEMP=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "##[set-output name=branch;]$(echo ${TEMP///-})"
        id: extract_ref_tag

      # Collate the image name, tags, and labels for push command
      - name: Extract metadata (tags, labels) for Docker
        if: steps.check_files.outputs.files_exists == 'true'
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ghcr.io/${{ inputs.image_name }}
          tags: |
            type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'main') }}
            type=raw,value=${{ steps.tag_version.outputs.new_tag }}
            type=raw,value=${{ steps.extract_ref_tag.outputs.branch }}
            type=raw,value=${{ GitHub.sha }}

      # Build, Tag and Push the docker image to Github Container Registry
      - name: Build, Tag and Push Docker Image
        if: steps.check_files.outputs.files_exists == 'true'
        uses: docker/build-push-action@v2.7.0
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Creates a Github release with the new semantic version
      - name: Create a GitHub Semantic release
        if: endsWith(GitHub.ref, 'main') && success()
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      
      # Sends a slack notification to slack build channel if Dockerfile is not present
      - name: Slack Notification - Dockerfile not Present
        if: steps.check_files.outputs.files_exists == 'false'
        uses: submittable/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: red
          SLACK_MESSAGE: Dockerfile not found!
          SLACK_FOOTER: Powered By Submittable GitHub Actions Library

      # Sends a slack notification to slack build channel on Success
      - name: Slack Notification - On Success
        if: endsWith(GitHub.ref, 'main') && success()
        uses: submittable/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Docker job for Release ${{ steps.tag_version.outputs.new_tag }} completed successfully!
          SLACK_FOOTER: Powered By Submittable GitHub Actions Library

      # Sends a slack notification to slack build channel on Failure
      - name: Slack Notification - On Failure
        if: endsWith(GitHub.ref, 'main') && failure()
        uses: submittable/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Docker job for Release ${{ steps.tag_version.outputs.new_tag }} FAILED!
          SLACK_FOOTER: Powered By Submittable GitHub Actions Library
